### ISSUE TITLE
错误反馈，是哪里不对？

### ISSUE THREAD

**Issue by skbamboo** [fffonion/xeHentai-webui#5]
[Feb 27 08:05:08] 绅士-down-3 下载图片 #3 时出错: 连接有问题？, 将在稍后重试
[Feb 27 08:05:09] 绅士-down-3 未捕获的异常
Traceback (most recent call last):
  File "xeHentai\worker.py", line 239, in run
  File "xeHentai\worker.py", line 136, in request
  File "xeHentai\filters.py", line 159, in _
  File "xeHentai\filters.py", line 250, in download_file
  File "xeHentai\core.py", line 299, in <lambda>
  File "xeHentai\task.py", line 225, in save_file
WindowsError: [Error 3] : u'K:\\xeHentai-2.0.2.3-\u7a33\u5b9a\u7248.exe\\(COMIC1\u260610) [Kurohonyasan (Yamashita Kurowo)] Amanogawa Kirara Riko to Mirai to Ero Nama Haishin Shoubu Anal demo Nan demo Misetekureru Choroi Namanushi ga PreCure datta Ken. (Mahou Tsukai PreCure, Go! Princess PreCure) [Chinese] [\u8138\u80bf\u6c49\u5316\u7ec4]'

**Comment by fffonion** [comment]
用的什么方式启动，以及用的是exe还是split版？
