### ISSUE TITLE
反馈错误

### ISSUE THREAD

**Issue by jieyuanmao** [fffonion/xeHentai-webui#7]
老大下载一直报错

WARN - [13:53:45] 绅士-main GET https://e-hentai.org/g/1702839/135fbedccb: HTTPSConnectionPool(host='104.20.26.25', port=443): Max retries exceeded with url: /g/1702839/135fbedccb (Caused by SSLError(SSLError(1, u'[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:727)'),))
WARN - [13:53:47] 绅士-main GET https://e-hentai.org/g/1702839/135fbedccb: HTTPSConnectionPool(host='104.20.26.25', port=443): Max retries exceeded with url: /g/1702839/135fbedccb (Caused by SSLError(SSLError(1, u'[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:727)'),))
WARN - [13:53:49] 绅士-main GET https://e-hentai.org/g/1702839/135fbedccb: HTTPSConnectionPool(host='104.20.27.25', port=443): Max retries exceeded with url: /g/1702839/135fbedccb (Caused by SSLError(SSLError(1, u'[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:727)'),))
WARN - [13:53:51] 绅士-main GET https://e-hentai.org/g/1702839/135fbedccb: HTTPSConnectionPool(host='104.20.26.25', port=443): Max retries exceeded with url: /g/1702839/135fbedccb (Caused by SSLError(SSLError(1, u'[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:727)'),))
WARN - [13:53:52] 绅士-main GET https://e-hentai.org/g/1702839/135fbedccb: HTTPSConnectionPool(host='104.20.26.25', port=443): Max retries exceeded with url: /g/1702839/135fbedccb (Caused by SSLError(SSLError(1, u'[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:727)'),))
WARN - [13:53:54] 绅士-main GET https://e-hentai.org/g/1702839/135fbedccb: HTTPSConnectionPool(host='104.20.26.25', port=443): Max retries exceeded with url: /g/1702839/135fbedccb (Caused by SSLError(SSLError(1, u'[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:727)'),))
WARN - [13:53:55] 绅士-main GET https://e-hentai.org/g/1702839/135fbedccb: HTTPSConnectionPool(host='104.20.27.25', port=443): Max retries exceeded with url: /g/1702839/135fbedccb (Caused by SSLError(SSLError(1, u'[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:727)'),))
WARN - [13:53:57] 绅士-main GET https://e-hentai.org/g/1702839/135fbedccb: HTTPSConnectionPool(host='104.20.26.25', port=443): Max retries exceeded with url: /g/1702839/135fbedccb (Caused by SSLError(SSLError(1, u'[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:727)'),))
WARN - [13:53:59] 绅士-main GET https://e-hentai.org/g/1702839/135fbedccb: HTTPSConnectionPool(host='104.20.26.25', port=443): Max retries exceeded with url: /g/1702839/135fbedccb (Caused by SSLError(SSLError(1, u'[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:727)'),))
WARN - [13:54:01] 绅士-main GET https://e-hentai.org/g/1702839/135fbedccb: HTTPSConnectionPool(host='104.20.27.25', port=443): Max retries exceeded with url: /g/1702839/135fbedccb (Caused by SSLError(SSLError(1, u'[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:727)'),))
ERROR - [13:54:01] 任务 #fe4696f5 发生错误: Traceback (most recent call last):
  File "xeHentai\core.py", line 205, in _do_task
  File "xeHentai\worker.py", line 138, in request
  File "xeHentai\filters.py", line 40, in flt_metadata
AttributeError: '_FakeResponse' object has no attribute 'text'

**Comment by jieyuanmao** [comment]
我是用exe版本
